CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    pseudo VARCHAR(50) NOT NULL UNIQUE,
    mail VARCHAR(255) NOT NULL UNIQUE,
    mdp VARCHAR(255) NOT NULL,
    pays VARCHAR(50) NOT NULL,
    photo LONGTEXT NULL, 
    dateCreation TIMESTAMP DEFAULT,CURRENT_TIMESTAMP
);
